INCLUDE "registers.inc"

INCLUDE "component/bugvm/vm_state.inc"
INCLUDE "component/bugvm/datastack.inc"
INCLUDE "component/lcdc/poke.inc"
INCLUDE "component/lcdc/vblank_irq.inc"
INCLUDE "component/system/banking.inc"
INCLUDE "component/spritemanager/animatesprites.inc"
INCLUDE "component/input/joypadstate.inc"
INCLUDE "component/nameinput/string_temporary.inc"

INCLUDE "component/patchsupport/readfile.inc"
INCLUDE "component/windowmanager/vwf_advice.inc"
